export let stat = {
 lastShotTime : 0,
  enemycount : 0,
  herolives : 2,
  enemies : [],
  SHOOT_DELAY : 200, 
  lastOne :false,
  lastOneLives : 19,
  sec :0,
  pause : false,
  rdm : 0,
  bulcount : 100,
  heroX : 0,
  heroY : 0,
  enemytotal : 0,
  heroBullets : [],
  enemyBullets : [],
  gameOver : false,
  lvl : 1,
  scorr : 0,
  angle : 0,
  speed : 1.3,
  enemiesKilled : 0,
  enemy1 : 'image/enemy1.png',
  enemy2 : 'image/enemy2.png',
  enemy3 : 'image/enemy3.png',
levelConfig : {
  1: { enemy: 'image/enemy1.png', maxAlive: 5, totalToKill: 10 },
  2: { enemy: 'image/enemy2.png', maxAlive: 8, totalToKill: 25 },
  3: { boss: true }},
  
}